version: 2.1

commands:
  print_pipeline_id:
    parameters: 
      to:
        default: 1
        type: integer
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID   

jobs:
  calling_pipelineID:
    docker:
      - image: circleci/node:13.8.0
    steps:
      -  print_pipeline_id   

  fail_job: 
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - run: exit 1 
      - run: 
          name: on error 
          command: echo "Hello Error!"
          when: on_fail   

workflows:
  my-workflow:
    jobs:
      - calling_pipelineID
      - fail_job
