version: 2.1

executors:
  my-executor:
    docker: 
      - image: circleci/node:13.8.0

commands:
  print_pipeline_id:
    parameters: 
      to:
        default: 1
        type: integer
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID   

  print_pipeline_url:
    parameters:
      to: 
        default: "url not found"
        type: string   
      steps:
        - run: echo  "Hello <<pipeline.project.git_url>>"

jobs:
  calling_pipelineID:
    executor: my-executor
    steps:
      -  print_pipeline_id   

  calling_pipelineURLID:
    executor: my-executor 
    steps: 
      - print_pipeline_url
           

workflows:
  my-workflow:
    jobs:
      - calling_pipelineID
      - calling_pipelineURLID:
          requires:
            - calling_pipelineID
